### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by klimacht** [LineMetrics/Rest-Api-Documentation#1]
Hi,

i am trying to read data from a lot of co2 sensors. Currently they are all under devices/hardware. 
How do i access them with the api?
I found out that if i create a new object on the dashboard it shows up when performing an api call to v2/children//
But i dont want to push every input of every sensor manually into this object. 
I didn't mange to get anything for data which showes up under devices. 
Thanks
Thomas

**Comment by LineMetricsDevs** [comment]
Sorry for the late reply. We are not handle issues here. If 'your issue is still relevant, please repost it at ticket.linemetrics.com or service@linemetrics.com

Thanks in advance,
Team LineMetrics
